"""
Template-Based Terraform Generator
Generates deterministic Terraform code from normalized architecture intent
NO LLM involvement - pure template rendering for consistency and cost savings
"""

import os
import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape
from typing import Dict, Optional
from pathlib import Path
from schemas.architecture_schema import ArchitectureIntent


class TerraformGenerator:
    """
    Template-based Terraform code generator
    CRITICAL: This uses Jinja2 templates - NO Bedrock/LLM calls
    Same input always produces same output (deterministic)
    """

    def __init__(
        self,
        templates_dir: str = "templates/terraform",
        service_registry_path: str = "registry/service_registry.yaml"
    ):
        """Initialize Jinja2 environment and load service registry"""

        self.templates_dir = templates_dir

        # Initialize Jinja2 environment
        self.jinja_env = Environment(
            loader=FileSystemLoader(templates_dir),
            autoescape=select_autoescape(['html', 'xml']),
            trim_blocks=True,
            lstrip_blocks=True
        )

        # Add custom filters
        self.jinja_env.filters['to_tf_identifier'] = self._to_tf_identifier
        self.jinja_env.filters['to_json'] = self._to_json

        # Load service registry
        with open(service_registry_path, 'r') as f:
            self.service_registry = yaml.safe_load(f)

    def generate(
        self,
        architecture: ArchitectureIntent,
        output_dir: str = "generated_terraform"
    ) -> Dict[str, str]:
        """
        Generate complete Terraform configuration from architecture intent

        Args:
            architecture: Normalized architecture intent
            output_dir: Output directory for Terraform files

        Returns:
            Dictionary mapping file names to their contents
        """

        # Create output directory
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        # Generate each Terraform file
        terraform_files = {}

        # 1. Main configuration (provider, data sources)
        terraform_files['main.tf'] = self._render_template(
            'main.tf.j2',
            architecture=architecture,
            service_registry=self.service_registry
        )

        # 2. Variables
        terraform_files['variables.tf'] = self._render_template(
            'variables.tf.j2',
            architecture=architecture
        )

        # 3. Networking
        terraform_files['networking.tf'] = self._render_template(
            'networking.tf.j2',
            architecture=architecture,
            service_registry=self.service_registry
        )

        # 4. Services
        terraform_files['services.tf'] = self._render_template(
            'services.tf.j2',
            architecture=architecture,
            service_registry=self.service_registry
        )

        # 5. Outputs
        terraform_files['outputs.tf'] = self._render_template(
            'outputs.tf.j2',
            architecture=architecture
        )

        # 6. README
        terraform_files['README.md'] = self._generate_readme(architecture)

        # 7. terraform.tfvars (optional - example values)
        terraform_files['terraform.tfvars.example'] = self._generate_tfvars_example(architecture)

        # Write files to disk
        for filename, content in terraform_files.items():
            file_path = os.path.join(output_dir, filename)
            with open(file_path, 'w') as f:
                f.write(content)

        return terraform_files

    def _render_template(self, template_name: str, **context) -> str:
        """Render a Jinja2 template with given context"""
        try:
            template = self.jinja_env.get_template(template_name)
            return template.render(**context)
        except Exception as e:
            raise Exception(f"Failed to render template {template_name}: {str(e)}")

    def _generate_readme(self, architecture: ArchitectureIntent) -> str:
        """Generate README.md for the Terraform project"""

        readme = f"""# {architecture.architecture_name}

## Overview

{architecture.description}

**Environment:** {architecture.environment.value}
**AWS Region:** {architecture.aws_region}
**Generated by:** DevGenius AI-IaC Platform
**Version:** {architecture.version}

## Architecture

### Services

"""

        # List all services
        for service in architecture.services:
            readme += f"- **{service.name}** ({service.service_type})\n"
            readme += f"  - Category: {service.category.value}\n"
            readme += f"  - Network Exposure: {service.network_exposure.value}\n"
            readme += f"  - High Availability: {service.high_availability.value}\n"
            readme += f"\n"

        readme += """
### Network Configuration

"""
        readme += f"- VPC CIDR: `{architecture.network.vpc_cidr}`\n"
        readme += f"- Availability Zones: {architecture.network.availability_zones}\n"
        readme += f"- NAT Gateway: {'Enabled' if architecture.network.enable_nat_gateway else 'Disabled'}\n"
        readme += f"- VPN: {'Enabled' if architecture.network.enable_vpn else 'Disabled'}\n"

        readme += """
## Prerequisites

1. **Terraform** >= 1.0
2. **AWS CLI** configured with appropriate credentials
3. **AWS Account** with necessary permissions

## Deployment

### 1. Initialize Terraform

```bash
terraform init
```

### 2. Review the Plan

```bash
terraform plan
```

### 3. Apply the Configuration

```bash
terraform apply
```

### 4. Destroy Resources (when needed)

```bash
terraform destroy
```

## Configuration

### Variables

Edit `terraform.tfvars` to customize the deployment:

```hcl
aws_region         = "{architecture.aws_region}"
environment        = "{architecture.environment.value}"
architecture_name  = "{architecture.architecture_name}"
```

### Environment-Specific Overrides

This Terraform configuration automatically applies environment-specific settings:

- **Production**: Multi-AZ databases, enhanced monitoring, backup retention
- **Development**: Single-AZ resources, minimal monitoring, cost optimization

## Security

"""

        if architecture.security.enable_encryption_at_rest:
            readme += "- ✅ Encryption at rest enabled\n"
        if architecture.security.enable_encryption_in_transit:
            readme += "- ✅ Encryption in transit enabled\n"
        if architecture.security.enable_logging:
            readme += "- ✅ Logging enabled\n"
        if architecture.security.enable_monitoring:
            readme += "- ✅ Monitoring enabled\n"
        if architecture.security.compliance_frameworks:
            readme += f"- ✅ Compliance frameworks: {', '.join(architecture.security.compliance_frameworks)}\n"

        readme += """
## Cost Optimization

"""

        if architecture.cost.budget_limit:
            readme += f"- Monthly budget limit: ${architecture.cost.budget_limit}\n"
        if architecture.cost.enable_cost_optimization:
            readme += "- ✅ Cost optimization enabled\n"
        if architecture.cost.enable_auto_scaling:
            readme += "- ✅ Auto-scaling enabled\n"

        readme += """
## Validation

Run the following commands to validate the Terraform configuration:

```bash
# Format check
terraform fmt -check

# Validation
terraform validate

# Security scan (requires Checkov)
checkov -d .

# Security scan (requires tfsec)
tfsec .
```

## Generated Files

- `main.tf` - Provider configuration and data sources
- `variables.tf` - Input variables
- `networking.tf` - VPC, subnets, and networking resources
- `services.tf` - Application services and resources
- `outputs.tf` - Output values

## Support

For issues or questions, please refer to the DevGenius documentation.

---

**Generated by DevGenius AI-IaC Platform**
**Timestamp:** {architecture.version}
"""

        return readme

    def _generate_tfvars_example(self, architecture: ArchitectureIntent) -> str:
        """Generate terraform.tfvars.example file"""

        tfvars = f"""# Terraform Variables Example
# Copy this file to terraform.tfvars and customize values

# Global Configuration
aws_region        = "{architecture.aws_region}"
environment       = "{architecture.environment.value}"
architecture_name = "{architecture.architecture_name}"

# Network Configuration
vpc_cidr                 = "{architecture.network.vpc_cidr}"
availability_zones_count = {architecture.network.availability_zones}
enable_nat_gateway       = {str(architecture.network.enable_nat_gateway).lower()}
enable_vpn_gateway       = {str(architecture.network.enable_vpn).lower()}

"""

        if architecture.cost.budget_limit:
            tfvars += f"""# Cost Configuration
monthly_budget_limit = {architecture.cost.budget_limit}

"""

        tfvars += """# Additional Tags
additional_tags = {
"""
        for key, value in architecture.tags.items():
            tfvars += f'  "{key}" = "{value}"\n'

        tfvars += "}\n"

        return tfvars

    def _to_tf_identifier(self, value: str) -> str:
        """Convert string to valid Terraform identifier"""
        import re
        # Replace invalid characters with underscores
        identifier = re.sub(r'[^a-zA-Z0-9_]', '_', str(value))
        # Ensure it doesn't start with a number
        if identifier and identifier[0].isdigit():
            identifier = f"_{identifier}"
        return identifier.lower()

    def _to_json(self, value) -> str:
        """Convert value to JSON string"""
        import json
        return json.dumps(value)

    def estimate_generation_cost(self) -> Dict[str, float]:
        """
        Estimate cost of Terraform generation
        Template-based generation has ZERO Bedrock cost!

        Returns:
            Cost breakdown (should be $0 for template generation)
        """
        return {
            "bedrock_cost_usd": 0.0,
            "total_cost_usd": 0.0,
            "note": "Template-based generation uses NO LLM - zero Bedrock cost!"
        }


# Example usage
if __name__ == "__main__":
    import json
    from schemas.architecture_schema import (
        ArchitectureIntent,
        ServiceIntent,
        Connection,
        Environment,
        ServiceCategory,
        NetworkExposure,
        HighAvailability
    )

    # Sample architecture intent
    sample_architecture = ArchitectureIntent(
        architecture_name="sample-web-app",
        description="Simple web application with database",
        environment=Environment.DEV,
        aws_region="us-east-1",
        services=[
            ServiceIntent(
                id="web-server",
                service_type="ec2",
                name="Web Server",
                category=ServiceCategory.COMPUTE,
                network_exposure=NetworkExposure.PUBLIC,
                high_availability=HighAvailability.SINGLE_AZ,
                configuration={
                    "instance_type": "t3.micro",
                    "ami": "data.aws_ami.amazon_linux_2023.id"
                }
            ),
            ServiceIntent(
                id="database",
                service_type="rds",
                name="PostgreSQL Database",
                category=ServiceCategory.DATABASE,
                network_exposure=NetworkExposure.PRIVATE,
                high_availability=HighAvailability.SINGLE_AZ,
                configuration={
                    "engine": "postgres",
                    "engine_version": "15.4",
                    "instance_class": "db.t3.micro"
                }
            )
        ],
        connections=[
            Connection(
                source="web-server",
                target="database",
                protocol="TCP",
                port=5432
            )
        ]
    )

    # Generate Terraform
    generator = TerraformGenerator()
    terraform_files = generator.generate(
        sample_architecture,
        output_dir="./test_terraform_output"
    )

    print("Generated Terraform files:")
    for filename in terraform_files.keys():
        print(f"  - {filename}")

    # Show cost (should be $0)
    cost = generator.estimate_generation_cost()
    print(f"\nGeneration cost: ${cost['total_cost_usd']}")
    print(f"Note: {cost['note']}")
